apiVersion: v1
kind: Service
metadata:
  name: spring-service-pipeline
spec:
  selectors:
    app: spring-pipeline-pod
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
