apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pipeline-pod
  template:
    metadata:
      labels:
        app: spring-pipeline-pod
    spec:
      containers:
        - name: spring-container
          image: thanak81/java-homework003-pipeline:1.0.0-10
          ports:
            - containerPort: 8080