apiVersion: v1
kind: Service
metadata:
  name: spring-service-pipeline
spec:
  selectors:
    app: spring-pipeline-pod
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30008
